sudo: false

cache: apt

addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-fonts-recommended 
    - texlive-fonts-extra
    - texlive-latex-recommended
    - dvipng

before_install:
 - chmod +x compile

script: ./compile

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
      - lucas@sciencestechniques.fr
    on_success: change # default: change
    on_failure: always

